server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis?useSSL=false&serverTimezone=UTC
    username: root
    password: xuxiaolei
#  redis:
#    data:
#      host: localhost
#      port: 6379
#      password: xuxiaolei
#      lettuce:
#        pool:
#          max-active: 10
#          max-idle: 10
#          min-idle: 1
#          time-between-eviction-runs: 10s
  data:
    redis:
      host: localhost
      port: 6379
      password: xuxiaolei
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug